# Docker-specific configuration
spring:
  # Docker database configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/taskmanagement
    username: ${POSTGRES_USER:taskmanagement}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  
  # Docker Redis configuration
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD:}

# Docker server configuration
server:
  port: 8080
  address: 0.0.0.0

# Docker management configuration
management:
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# Docker logging configuration
logging:
  level:
    com.taskmanagement: INFO
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%replace(%msg){"\"","\\\""}","container":"task-management-api"}%n'

# Docker-specific CORS (allow container network)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://frontend:3000}

# Docker health check configuration
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true